language: java

jdk:
  - openjdk11

os:
  - linux

notifications:
  slack: bioprimeworkspace:$SLACK_TOKEN

jobs:
  include:
    - stage: build
      script: mvn clean compile
    - stage: test
      script: mvn test
    - stage: package
      script: mvn package
    - stage: build docker image
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build -t $DOCKER_USERNAME/backend:latest -t $DOCKER_USERNAME/backend:$TRAVIS_JOB_NUMBER .
        - docker push $DOCKER_USERNAME/backend:latest
        - docker push $DOCKER_USERNAME/backend:$TRAVIS_JOB_NUMBER