language: java

jdk:
  - openjdk11

os:
  - linux

notifications:
  slack: bioprimeworkspace:PeSqLEmvdR8KucSYVLSPBzWU

jobs:
  include:
    - stage: build
      script: mvn clean compile
    - stage: test
      script: mvn test
    - stage: package
      script: mvn package