version: '3'
services:
  frontend:
    image: "bioprime/frontend:latest"
    ports:
      - "80:80"
  backend:
    image: "bioprime/backend:latest"
    environment:
      - DB_USER=postgres
      - DB_PW=postgres
      - JDBC_URL=jdbc:postgresql://db/bioprime
    ports:
      - "8080:8080"
      - "8081:8081"
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bioprime
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: